Vagrant.configure("2") do |config|

  # Box seçimi
  config.vm.box         = "bento/ubuntu-24.04"
  config.vm.box_version = "202502.21.0"

  # VirtualBox kaynak kısıtlaması
  config.vm.provider "virtualbox" do |vb|
    vb.cpus   = 2
    vb.memory = 1536
  end

  # -------- Controller (Server) --------
  config.vm.define "msevukS" do |server|
    server.vm.hostname = "msevukS"
    server.vm.network  "private_network", ip: "192.168.56.110"

    server.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y curl
      curl -sfL https://get.k3s.io \
        | INSTALL_K3S_EXEC="--write-kubeconfig-mode=644" sh -
      sudo cat /var/lib/rancher/k3s/server/node-token > /vagrant/node-token
    SHELL
  end

  # -------- Agent (ServerWorker) --------
  config.vm.define "msevukSW" do |worker|
    worker.vm.hostname = "msevukSW"
    worker.vm.network  "private_network", ip: "192.168.56.111"

    worker.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y curl
      TOKEN=$(cat /vagrant/node-token)
      curl -sfL https://get.k3s.io \
        | K3S_URL=https://192.168.56.110:6443 \
          K3S_TOKEN=$TOKEN sh -
    SHELL
  end
end