SERVER_IP = "192.168.56.110"
WORKER_IP = "192.168.56.111"

SERVER_HOSTNAME = "muralerS"
WORKER_HOSTNAME = "muralerSW"

IMAGE = "ubuntu/jammy64"
IMAGE_VERSION = "20241002.0.0"

MEMORY = "2048"
CPUS = 2

Vagrant.configure("2") do |config|
  config.vm.box = IMAGE
  config.vm.box_version = IMAGE_VERSION
  config.vm.synced_folder ".", "/vagrant"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = MEMORY
    vb.cpus = CPUS
  end

  # Master node
  config.vm.define SERVER_HOSTNAME do |server|
    server.vm.hostname = SERVER_HOSTNAME
    server.vm.network "private_network", ip: SERVER_IP
    server.vm.provision "shell", path: "./scripts/master-setup.sh"
  end

  # Worker node
  config.vm.define WORKER_HOSTNAME do |worker|
    worker.vm.hostname = WORKER_HOSTNAME
    worker.vm.network "private_network", ip: WORKER_IP
    worker.vm.provision "shell", path: "./scripts/worker-setup.sh"
  end
end
