SERVER_IP = "192.168.56.110"
WORKER_IP = "192.168.56.111"

SERVER_HOSTNAME = "muralerS"
WORKER_HOSTNAME = "muralerSW"

IMAGE =  "generic/rocky8"
IMAGE_VERSION = "4.3.12"

MEMORY = "2048"
CPUS = 2 

Vagrant.configure("2") do |config|
  config.vm.box = IMAGE
  config.vm.box_version = IMAGE_VERSION
  config.vm.synced_folder ".", "/vagrant"
  # config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider "virtualbox" do |vb|
    vb.memory = MEMORY
    vb.cpus = CPUS
  end

  config.vm.define SERVER_HOSTNAME do |server|
    server.vm.hostname = SERVER_HOSTNAME
    server.vm.network "private_network", ip: SERVER_IP
  end

  config.vm.define WORKER_HOSTNAME do |worker|
    worker.vm.hostname = WORKER_HOSTNAME
    worker.vm.network "private_network", ip: WORKER_IP
  end
end