Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = "2"
  end

  # Forward ports needed for GitLab, ArgoCD, and the application
  config.vm.network "forwarded_port", guest: 8080, host: 8080 # k3d loadbalancer for HTTP
  config.vm.network "forwarded_port", guest: 8443, host: 8443 # k3d loadbalancer for HTTPS
  config.vm.network "forwarded_port", guest: 8888, host: 8888 # my-app service
  config.vm.network "forwarded_port", guest: 8081, host: 8081 # Potential ArgoCD port
  config.vm.network "forwarded_port", guest: 8082, host: 8082 # Potential ArgoCD port
  config.vm.network "forwarded_port", guest: 8083, host: 8083 # Potential ArgoCD port

  # Run the main setup script
  config.vm.provision "shell", path: "scripts/setup.sh"

end
