Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.network "forwarded_port", guest: 80, host: 8082
  config.vm.network "forwarded_port", guest: 443, host: 8444

  config.vm.provider "virtualbox" do |vb|
    vb.name = "gitlab-vm"
    vb.memory = "4096"
    vb.cpus = 2
  end

  config.vm.provision "shell", path: "install_gitlab.sh"
end


